language: php
php:
  - '5.6'
  - '7.0'
before_script:
  - phpenv config-rm xdebug.ini
  - travis_retry composer self-update
  - travis_retry composer update --prefer-source --prefer-stable
script: phpunit
branches:
  only:
  - master
  - stable
