language: php
php:
  - '5.6'
  - '7.0'
before_script:
  - phpenv config-rm xdebug.ini
  - composer update --prefer-source --prefer-stable
  - phpenv config-add xdebug.ini
script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml
after_script:
  - php vendor/bin/coveralls -v
branches:
  only:
  - master
  - stable
